### ISSUE TITLE
Unknown error(Debug.log)

### ISSUE THREAD

**Issue by Triftw** [IoTtalk/Dummy_Device_IoTtalk_v2_unity#1]
Got Unknown error with unity
version: 2019.2.5f1
I have gone through all the steps in Readme
Got the following errors and found out this may be .Net 2.0 standard problem,
so I changed the API compatibility level to .Net 4.x in player settings.
Assets\IoTtalk\IoTTalkV2DAI.cs(72,14): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
Assets\IoTtalk\IoTTalkV2DAI.cs(89,9): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'

After all this, I pressed play and got Unknown error(Debug.Log)
IOTTalkV2DAN.cs line 222

For the string api_url in IoTTalkV2SA(line 14)
I have tried both the original url and http://140.113.199.211:81/csm
both with same result(Unknown error)

![image](https://user-images.githubusercontent.com/34067626/113254602-64c3d600-92f9-11eb-99a5-20b0f93cee7f.png)

**Comment by yct0401** [comment]
Indeed, must changed the API compatibility level to .Net 4.x in player settings for using _dynamic_ keyword.
I forget writing in the Readme. I will update Readme later.
The problem probably is caused by main function executing too early.
It executed before SA object initialize. Incomplete register information will cause registration failure.
So comment main function in DAI start() and excute it manually ( such as  a button ).
It might solve your problem.
I test the way in unity 2019.2.5f1 and it work.

**Comment by Triftw** [comment]
![image](https://user-images.githubusercontent.com/34067626/114803733-96956c00-9dd2-11eb-8624-3a5572f88f5f.png)
I did execute main() with button and register successfully.
However, I can't find the device on iottalk server.
The api_url is http://140.113.199.211:81/csm
莊婷伃 gave me the server log below
![image](https://user-images.githubusercontent.com/34067626/114803759-a614b500-9dd2-11eb-9021-796b3be4d8dc.png)

**Comment by yct0401** [comment]
Maybe api_url did not cahnge. **api_url** in script is a public varible.
In Unity, public varible in instantiated object would not be change when the varible is changed in script.
Make sure **api_url** is changed in Inspector of sa object.

**Comment by yct0401** [comment]
@Triftw I update `IoTTalkV2SA.cs` and `IoTTalkV2DAN.cs`.
The problem of main function executed before SA object initialized  would be solved.

**Comment by Triftw** [comment]
It now works properly with the default url.
But It seems like Unity isn't compatible with IP address like the one I mentioned(http://140.113.199.211:81/csm)
We'll use a device with domain name for now.
Anyway, thank you for this project and answering this issue.

**Comment by yct0401** [comment]
I updated `IoTTalkV2DAN.cs`  yesterday to solve the problem of  IP address resolution failure.
`Net.Dns.GetHostEntry()`  occurred error when directly passing an IP address in .Net 4.X .
In this [article](https://stackoverflow.com/questions/2714449/) mentioned the problem.
If there is necessary to  use a device with IP address , new DAN script might work.
